version: '3.8'

services:
  app:
    container_name: openpadprotocol-verifiernode
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: production
      # PRIVATE_KEY: 'a5173d5eae835f1af8724819420677ae0a494dc26bb8a1fd374c1df01bdcb3ab'
      PRIVATE_KEY: 5bb057bd90634912db7621670d6aa5b068b5c19120787358e69369c50ce077d6
      CLAIMER_ADDRESS: '0x8c460C6c132332C2B2524a96e771864aD36BA945'
      COMMISSION_RATE: 10
      URL_API_OPENPAD: https://dev-api.openpad.io/api
      ADDRESS_ARBITRUM_SMC_OPERATION: '0xfDe45b0F52f56960bCeaF8c836670aE8808d35Dc'
      NETWORK_ARBITRUM: test
